# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   # name: {{ .Values.storage.class }}
#   name: {{ .Release.Namespace }}-storage-{{ .Release.Name }}
# provisioner: driver.longhorn.io
# reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
# volumeBindingMode: {{ .Values.storage.volumeBindingMode }}

