apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: orderer1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/fabric-orderernode
  values:
    global:
      version: 2.5.4
      serviceAccountName: vault-auth
      cluster:
        provider: k3s_longhorn
        cloudNativeServices: false
      vault:
        type: hashicorp
        network: fabric
        address: https://vault1.marketscloud.ng:8200
        authPath: devsupplychain
        secretEngine: secretsv2
        secretPrefix: "data/devsupplychain"
        role: vault-role
        tls: false
      proxy:
        provider: haproxy
        externalUrlSuffix: 192.168.0.72.nip.io

    storage:
      size: 512Mi
      reclaimPolicy: "Delete" 
      volumeBindingMode: 
      allowedTopologies:
        enabled: false

    certs:
      generateCertificates: true
      orgData:
        caAddress: ca.supplychain-net.192.168.0.72.nip.io
        caAdminUser: supplychain-admin
        caAdminPassword: supplychain-adminpw
        orgName: supplychain
        type: orderer
        componentSubject: "supplychain-net-supplychain"

      settings:
        createConfigMaps: True
        refreshCertValue: false
        addPeerValue: false
        removeCertsOnDelete: true
        removeOrdererTlsOnDelete: true

    image:
      orderer: ghcr.io/hyperledger/bevel-fabric-orderer
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      pullSecret: ""

    orderer:
      consensus: raft
      logLevel: info
      localMspId: supplychainMSP
      tlsStatus: true
      keepAliveServerInterval: 10s
      serviceType: ClusterIP
      ports:
        grpc:
          clusterIpPort: 7050
        metrics: 
          enabled: False
          clusterIpPort: 9443
      resources:
        limits:
          memory: 512M
          cpu: 1
        requests:
          memory: 512M
          cpu: 0.25


    healthCheck: 
      retries: 10
      sleepTimeAfterError: 15

      labels:
        service:
          - example1: example2
        pvc:
        deployment:
